namespace Academic.Domain.Students;

/// <summary>
/// Owned entity representing the enrollment record of a student.
/// Created atomically with the Student aggregate — cannot exist independently (ESC-12).
/// </summary>
public sealed class Enrollment
{
    public string   EnrollmentId { get; }   // 26-char ULID, generated by handler
    public DateTime CreatedAt    { get; }   // UTC

    internal Enrollment(string enrollmentId, DateTime createdAt)
    {
        EnrollmentId = enrollmentId;
        CreatedAt    = createdAt;
    }

    // EF Core parameterless constructor
    private Enrollment() { EnrollmentId = default!; }
}
